import bycrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "admin",
      email: "arthurginho02@gmail.com",
      password: bycrypt.hashSync("admin", 8),
      isAdmin: true,
    },
    {
      name: "zezin",
      email: "arthurginho03@gmail.com",
      password: bycrypt.hashSync("123", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "camisa branca",
      category: "camisas",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 14,
      brand: "Nike",
      rating: 1.5,
      numReviews: 17,
      description: "produto de alta qualidade",
    },
    {
      name: "camisa preta",
      category: "camisas",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 50,
      brand: "Nike",
      rating: 2.5,
      numReviews: 1,
      description: "produto de alta qualidade",
    },
    {
      name: "camisa amarela",
      category: "camisas",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 60,
      description: "produto de alta qualidade",
    },
    {
      name: "camisa azul",
      category: "camisas",
      image: "/images/p2.jpg",
      price: 200,
      countInStock: 0,
      brand: "Lacoste",
      rating: 4.5,
      numReviews: 0,
      description: "produto de alta qualidade",
    },
    {
      name: "camisa verde",
      category: "camisas",
      image: "/images/p2.jpg",
      price: 300,
      countInStock: 20,
      brand: "Oakley",
      rating: 4.5,
      numReviews: 5,
      description: "produto de alta qualidade",
    },
  ],
};
export default data;
