export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUES";
export const ORDER_CREATE_RESET = "ORDER_CREATE_REQUES";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_REQUES";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_REQUES";
export const CART_EMPTY = "CART_EMPTY";
